// Code generated by protoc-gen-gogo.
// source: internal/internal.proto
// DO NOT EDIT!

/*
Package influxql is a generated protocol buffer package.

It is generated from these files:
	internal/internal.proto

It has these top-level messages:
	Point
	Aux
	IteratorOptions
	Measurements
	Measurement
	Interval
	IteratorStats
	VarRef
*/
package influxql

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Point struct {
	Name             *string        `protobuf:"bytes,1,req,name=Name,json=name" json:"Name,omitempty"`
	Tags             *string        `protobuf:"bytes,2,req,name=Tags,json=tags" json:"Tags,omitempty"`
	Time             *int64         `protobuf:"varint,3,req,name=Time,json=time" json:"Time,omitempty"`
	Nil              *bool          `protobuf:"varint,4,req,name=Nil,json=nil" json:"Nil,omitempty"`
	Aux              []*Aux         `protobuf:"bytes,5,rep,name=Aux,json=aux" json:"Aux,omitempty"`
	Aggregated       *uint32        `protobuf:"varint,6,opt,name=Aggregated,json=aggregated" json:"Aggregated,omitempty"`
	FloatValue       *float64       `protobuf:"fixed64,7,opt,name=FloatValue,json=floatValue" json:"FloatValue,omitempty"`
	IntegerValue     *int64         `protobuf:"varint,8,opt,name=IntegerValue,json=integerValue" json:"IntegerValue,omitempty"`
	StringValue      *string        `protobuf:"bytes,9,opt,name=StringValue,json=stringValue" json:"StringValue,omitempty"`
	BooleanValue     *bool          `protobuf:"varint,10,opt,name=BooleanValue,json=booleanValue" json:"BooleanValue,omitempty"`
	Stats            *IteratorStats `protobuf:"bytes,11,opt,name=Stats,json=stats" json:"Stats,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Point) Reset()                    { *m = Point{} }
func (m *Point) String() string            { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()               {}
func (*Point) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{0} }

func (m *Point) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Point) GetTags() string {
	if m != nil && m.Tags != nil {
		return *m.Tags
	}
	return ""
}

func (m *Point) GetTime() int64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Point) GetNil() bool {
	if m != nil && m.Nil != nil {
		return *m.Nil
	}
	return false
}

func (m *Point) GetAux() []*Aux {
	if m != nil {
		return m.Aux
	}
	return nil
}

func (m *Point) GetAggregated() uint32 {
	if m != nil && m.Aggregated != nil {
		return *m.Aggregated
	}
	return 0
}

func (m *Point) GetFloatValue() float64 {
	if m != nil && m.FloatValue != nil {
		return *m.FloatValue
	}
	return 0
}

func (m *Point) GetIntegerValue() int64 {
	if m != nil && m.IntegerValue != nil {
		return *m.IntegerValue
	}
	return 0
}

func (m *Point) GetStringValue() string {
	if m != nil && m.StringValue != nil {
		return *m.StringValue
	}
	return ""
}

func (m *Point) GetBooleanValue() bool {
	if m != nil && m.BooleanValue != nil {
		return *m.BooleanValue
	}
	return false
}

func (m *Point) GetStats() *IteratorStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Aux struct {
	DataType         *int32   `protobuf:"varint,1,req,name=DataType,json=dataType" json:"DataType,omitempty"`
	FloatValue       *float64 `protobuf:"fixed64,2,opt,name=FloatValue,json=floatValue" json:"FloatValue,omitempty"`
	IntegerValue     *int64   `protobuf:"varint,3,opt,name=IntegerValue,json=integerValue" json:"IntegerValue,omitempty"`
	StringValue      *string  `protobuf:"bytes,4,opt,name=StringValue,json=stringValue" json:"StringValue,omitempty"`
	BooleanValue     *bool    `protobuf:"varint,5,opt,name=BooleanValue,json=booleanValue" json:"BooleanValue,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Aux) Reset()                    { *m = Aux{} }
func (m *Aux) String() string            { return proto.CompactTextString(m) }
func (*Aux) ProtoMessage()               {}
func (*Aux) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{1} }

func (m *Aux) GetDataType() int32 {
	if m != nil && m.DataType != nil {
		return *m.DataType
	}
	return 0
}

func (m *Aux) GetFloatValue() float64 {
	if m != nil && m.FloatValue != nil {
		return *m.FloatValue
	}
	return 0
}

func (m *Aux) GetIntegerValue() int64 {
	if m != nil && m.IntegerValue != nil {
		return *m.IntegerValue
	}
	return 0
}

func (m *Aux) GetStringValue() string {
	if m != nil && m.StringValue != nil {
		return *m.StringValue
	}
	return ""
}

func (m *Aux) GetBooleanValue() bool {
	if m != nil && m.BooleanValue != nil {
		return *m.BooleanValue
	}
	return false
}

type IteratorOptions struct {
	Expr             *string        `protobuf:"bytes,1,opt,name=Expr,json=expr" json:"Expr,omitempty"`
	Aux              []string       `protobuf:"bytes,2,rep,name=Aux,json=aux" json:"Aux,omitempty"`
	Fields           []*VarRef      `protobuf:"bytes,17,rep,name=Fields,json=fields" json:"Fields,omitempty"`
	Sources          []*Measurement `protobuf:"bytes,3,rep,name=Sources,json=sources" json:"Sources,omitempty"`
	Interval         *Interval      `protobuf:"bytes,4,opt,name=Interval,json=interval" json:"Interval,omitempty"`
	Dimensions       []string       `protobuf:"bytes,5,rep,name=Dimensions,json=dimensions" json:"Dimensions,omitempty"`
	Fill             *int32         `protobuf:"varint,6,opt,name=Fill,json=fill" json:"Fill,omitempty"`
	FillValue        *float64       `protobuf:"fixed64,7,opt,name=FillValue,json=fillValue" json:"FillValue,omitempty"`
	Condition        *string        `protobuf:"bytes,8,opt,name=Condition,json=condition" json:"Condition,omitempty"`
	StartTime        *int64         `protobuf:"varint,9,opt,name=StartTime,json=startTime" json:"StartTime,omitempty"`
	EndTime          *int64         `protobuf:"varint,10,opt,name=EndTime,json=endTime" json:"EndTime,omitempty"`
	Ascending        *bool          `protobuf:"varint,11,opt,name=Ascending,json=ascending" json:"Ascending,omitempty"`
	Limit            *int64         `protobuf:"varint,12,opt,name=Limit,json=limit" json:"Limit,omitempty"`
	Offset           *int64         `protobuf:"varint,13,opt,name=Offset,json=offset" json:"Offset,omitempty"`
	SLimit           *int64         `protobuf:"varint,14,opt,name=SLimit,json=sLimit" json:"SLimit,omitempty"`
	SOffset          *int64         `protobuf:"varint,15,opt,name=SOffset,json=sOffset" json:"SOffset,omitempty"`
	Dedupe           *bool          `protobuf:"varint,16,opt,name=Dedupe,json=dedupe" json:"Dedupe,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *IteratorOptions) Reset()                    { *m = IteratorOptions{} }
func (m *IteratorOptions) String() string            { return proto.CompactTextString(m) }
func (*IteratorOptions) ProtoMessage()               {}
func (*IteratorOptions) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{2} }

func (m *IteratorOptions) GetExpr() string {
	if m != nil && m.Expr != nil {
		return *m.Expr
	}
	return ""
}

func (m *IteratorOptions) GetAux() []string {
	if m != nil {
		return m.Aux
	}
	return nil
}

func (m *IteratorOptions) GetFields() []*VarRef {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *IteratorOptions) GetSources() []*Measurement {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *IteratorOptions) GetInterval() *Interval {
	if m != nil {
		return m.Interval
	}
	return nil
}

func (m *IteratorOptions) GetDimensions() []string {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *IteratorOptions) GetFill() int32 {
	if m != nil && m.Fill != nil {
		return *m.Fill
	}
	return 0
}

func (m *IteratorOptions) GetFillValue() float64 {
	if m != nil && m.FillValue != nil {
		return *m.FillValue
	}
	return 0
}

func (m *IteratorOptions) GetCondition() string {
	if m != nil && m.Condition != nil {
		return *m.Condition
	}
	return ""
}

func (m *IteratorOptions) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *IteratorOptions) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func (m *IteratorOptions) GetAscending() bool {
	if m != nil && m.Ascending != nil {
		return *m.Ascending
	}
	return false
}

func (m *IteratorOptions) GetLimit() int64 {
	if m != nil && m.Limit != nil {
		return *m.Limit
	}
	return 0
}

func (m *IteratorOptions) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

func (m *IteratorOptions) GetSLimit() int64 {
	if m != nil && m.SLimit != nil {
		return *m.SLimit
	}
	return 0
}

func (m *IteratorOptions) GetSOffset() int64 {
	if m != nil && m.SOffset != nil {
		return *m.SOffset
	}
	return 0
}

func (m *IteratorOptions) GetDedupe() bool {
	if m != nil && m.Dedupe != nil {
		return *m.Dedupe
	}
	return false
}

type Measurements struct {
	Items            []*Measurement `protobuf:"bytes,1,rep,name=Items,json=items" json:"Items,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Measurements) Reset()                    { *m = Measurements{} }
func (m *Measurements) String() string            { return proto.CompactTextString(m) }
func (*Measurements) ProtoMessage()               {}
func (*Measurements) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{3} }

func (m *Measurements) GetItems() []*Measurement {
	if m != nil {
		return m.Items
	}
	return nil
}

type Measurement struct {
	Database         *string `protobuf:"bytes,1,opt,name=Database,json=database" json:"Database,omitempty"`
	RetentionPolicy  *string `protobuf:"bytes,2,opt,name=RetentionPolicy,json=retentionPolicy" json:"RetentionPolicy,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=Name,json=name" json:"Name,omitempty"`
	Regex            *string `protobuf:"bytes,4,opt,name=Regex,json=regex" json:"Regex,omitempty"`
	IsTarget         *bool   `protobuf:"varint,5,opt,name=IsTarget,json=isTarget" json:"IsTarget,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Measurement) Reset()                    { *m = Measurement{} }
func (m *Measurement) String() string            { return proto.CompactTextString(m) }
func (*Measurement) ProtoMessage()               {}
func (*Measurement) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{4} }

func (m *Measurement) GetDatabase() string {
	if m != nil && m.Database != nil {
		return *m.Database
	}
	return ""
}

func (m *Measurement) GetRetentionPolicy() string {
	if m != nil && m.RetentionPolicy != nil {
		return *m.RetentionPolicy
	}
	return ""
}

func (m *Measurement) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Measurement) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *Measurement) GetIsTarget() bool {
	if m != nil && m.IsTarget != nil {
		return *m.IsTarget
	}
	return false
}

type Interval struct {
	Duration         *int64 `protobuf:"varint,1,opt,name=Duration,json=duration" json:"Duration,omitempty"`
	Offset           *int64 `protobuf:"varint,2,opt,name=Offset,json=offset" json:"Offset,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Interval) Reset()                    { *m = Interval{} }
func (m *Interval) String() string            { return proto.CompactTextString(m) }
func (*Interval) ProtoMessage()               {}
func (*Interval) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{5} }

func (m *Interval) GetDuration() int64 {
	if m != nil && m.Duration != nil {
		return *m.Duration
	}
	return 0
}

func (m *Interval) GetOffset() int64 {
	if m != nil && m.Offset != nil {
		return *m.Offset
	}
	return 0
}

type IteratorStats struct {
	SeriesN          *int64 `protobuf:"varint,1,opt,name=SeriesN,json=seriesN" json:"SeriesN,omitempty"`
	PointN           *int64 `protobuf:"varint,2,opt,name=PointN,json=pointN" json:"PointN,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IteratorStats) Reset()                    { *m = IteratorStats{} }
func (m *IteratorStats) String() string            { return proto.CompactTextString(m) }
func (*IteratorStats) ProtoMessage()               {}
func (*IteratorStats) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{6} }

func (m *IteratorStats) GetSeriesN() int64 {
	if m != nil && m.SeriesN != nil {
		return *m.SeriesN
	}
	return 0
}

func (m *IteratorStats) GetPointN() int64 {
	if m != nil && m.PointN != nil {
		return *m.PointN
	}
	return 0
}

type VarRef struct {
	Val              *string `protobuf:"bytes,1,req,name=Val,json=val" json:"Val,omitempty"`
	Type             *int32  `protobuf:"varint,2,opt,name=Type,json=type" json:"Type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VarRef) Reset()                    { *m = VarRef{} }
func (m *VarRef) String() string            { return proto.CompactTextString(m) }
func (*VarRef) ProtoMessage()               {}
func (*VarRef) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{7} }

func (m *VarRef) GetVal() string {
	if m != nil && m.Val != nil {
		return *m.Val
	}
	return ""
}

func (m *VarRef) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*Point)(nil), "influxql.Point")
	proto.RegisterType((*Aux)(nil), "influxql.Aux")
	proto.RegisterType((*IteratorOptions)(nil), "influxql.IteratorOptions")
	proto.RegisterType((*Measurements)(nil), "influxql.Measurements")
	proto.RegisterType((*Measurement)(nil), "influxql.Measurement")
	proto.RegisterType((*Interval)(nil), "influxql.Interval")
	proto.RegisterType((*IteratorStats)(nil), "influxql.IteratorStats")
	proto.RegisterType((*VarRef)(nil), "influxql.VarRef")
}

func init() { proto.RegisterFile("internal/internal.proto", fileDescriptorInternal) }

var fileDescriptorInternal = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x6a, 0xe4, 0x36,
	0x14, 0xc6, 0x7f, 0x33, 0xb6, 0x66, 0xd2, 0xa4, 0x62, 0xdb, 0x15, 0xa5, 0xb4, 0xc6, 0x57, 0x86,
	0xd2, 0x59, 0xc8, 0x6d, 0xa1, 0x30, 0x6d, 0x36, 0x10, 0x68, 0x93, 0x45, 0x13, 0x72, 0xaf, 0x8d,
	0x8f, 0x8d, 0x40, 0x96, 0x5d, 0x49, 0x2e, 0x93, 0xbb, 0xbe, 0x46, 0x9f, 0xa1, 0x0f, 0xd3, 0x57,
	0x2a, 0x3a, 0xb6, 0x67, 0xbc, 0x2d, 0x34, 0x57, 0xf6, 0xf7, 0x9d, 0xa3, 0x9f, 0xef, 0x9c, 0x4f,
	0x87, 0xbc, 0x95, 0xda, 0x81, 0xd1, 0x42, 0xbd, 0x9b, 0x7f, 0x76, 0xbd, 0xe9, 0x5c, 0x47, 0x53,
	0xa9, 0x6b, 0x35, 0x1c, 0x7f, 0x53, 0xc5, 0xdf, 0x21, 0x49, 0x3e, 0x74, 0x52, 0x3b, 0x4a, 0x49,
	0x7c, 0x2f, 0x5a, 0x60, 0x41, 0x1e, 0x96, 0x19, 0x8f, 0xb5, 0x68, 0xc1, 0x73, 0x8f, 0xa2, 0xb1,
	0x2c, 0x1c, 0x39, 0x27, 0x1a, 0x8b, 0x9c, 0x6c, 0x81, 0x45, 0x79, 0x58, 0x46, 0x3c, 0x76, 0xb2,
	0x05, 0x7a, 0x45, 0xa2, 0x7b, 0xa9, 0x58, 0x9c, 0x87, 0x65, 0xca, 0x23, 0x2d, 0x15, 0xfd, 0x96,
	0x44, 0xfb, 0xe1, 0xc8, 0x92, 0x3c, 0x2a, 0x37, 0xd7, 0x17, 0xbb, 0xf9, 0xbc, 0xdd, 0x7e, 0x38,
	0xf2, 0x48, 0x0c, 0x47, 0xfa, 0x0d, 0x21, 0xfb, 0xa6, 0x31, 0xd0, 0x08, 0x07, 0x15, 0x5b, 0xe5,
	0x41, 0x79, 0xc1, 0x89, 0x38, 0x31, 0x3e, 0x7e, 0xab, 0x3a, 0xe1, 0x9e, 0x84, 0x1a, 0x80, 0xad,
	0xf3, 0xa0, 0x0c, 0x38, 0xa9, 0x4f, 0x0c, 0x2d, 0xc8, 0xf6, 0x4e, 0x3b, 0x68, 0xc0, 0x8c, 0x19,
	0x69, 0x1e, 0x94, 0x11, 0xdf, 0xca, 0x05, 0x47, 0x73, 0xb2, 0x39, 0x38, 0x23, 0x75, 0x33, 0xa6,
	0x64, 0x79, 0x50, 0x66, 0x7c, 0x63, 0xcf, 0x94, 0xdf, 0xe5, 0xa7, 0xae, 0x53, 0x20, 0xf4, 0x98,
	0x42, 0xf2, 0xa0, 0x4c, 0xf9, 0xf6, 0xe3, 0x82, 0xa3, 0xdf, 0x93, 0xe4, 0xe0, 0x84, 0xb3, 0x6c,
	0x93, 0x07, 0xe5, 0xe6, 0xfa, 0xed, 0x59, 0xcc, 0x9d, 0x03, 0x23, 0x5c, 0x67, 0x30, 0xcc, 0x13,
	0xeb, 0x3f, 0xc5, 0x5f, 0x01, 0x4a, 0xa7, 0x5f, 0x91, 0xf4, 0x46, 0x38, 0xf1, 0xf8, 0xd2, 0x8f,
	0x35, 0x4d, 0x78, 0x5a, 0x4d, 0xf8, 0x5f, 0xe2, 0xc2, 0x57, 0xc5, 0x45, 0xaf, 0x8b, 0x8b, 0x5f,
	0x17, 0x97, 0xfc, 0x57, 0x5c, 0xf1, 0x47, 0x4c, 0x2e, 0x67, 0x19, 0x0f, 0xbd, 0x93, 0x9d, 0xc6,
	0x0e, 0xbf, 0x3f, 0xf6, 0x86, 0x05, 0xb8, 0x65, 0x0c, 0xc7, 0xde, 0xf8, 0x0e, 0xfb, 0x7e, 0x86,
	0x79, 0x54, 0x66, 0x63, 0x03, 0x4b, 0xb2, 0xba, 0x95, 0xa0, 0x2a, 0xcb, 0x3e, 0xc7, 0x26, 0x5f,
	0x9d, 0xeb, 0xf2, 0x24, 0x0c, 0x87, 0x9a, 0xaf, 0x6a, 0x8c, 0xd3, 0x77, 0x64, 0x7d, 0xe8, 0x06,
	0xf3, 0x0c, 0x96, 0x45, 0x98, 0xfa, 0xc5, 0x39, 0xf5, 0x57, 0x10, 0x76, 0x30, 0xd0, 0x82, 0x76,
	0x7c, 0x6d, 0xc7, 0x2c, 0xba, 0x23, 0xa9, 0x97, 0x6f, 0x7e, 0x17, 0x0a, 0x75, 0x6d, 0xae, 0xe9,
	0xa2, 0xe8, 0x53, 0x84, 0xa7, 0x72, 0xfa, 0xf3, 0xe5, 0xbc, 0x91, 0x2d, 0x68, 0xeb, 0xaf, 0x8f,
	0x9e, 0xcb, 0x38, 0xa9, 0x4e, 0x8c, 0x17, 0x74, 0x2b, 0x95, 0x42, 0x97, 0x25, 0x3c, 0xae, 0xa5,
	0x52, 0xf4, 0x6b, 0x92, 0x79, 0x6e, 0x69, 0xaf, 0xac, 0x9e, 0x09, 0x1f, 0xfd, 0xb9, 0xd3, 0x95,
	0xf4, 0x05, 0x41, 0x6b, 0x65, 0x3c, 0x7b, 0x9e, 0x09, 0x1f, 0x3d, 0x38, 0x61, 0x1c, 0xbe, 0x83,
	0x0c, 0x7b, 0x93, 0xd9, 0x99, 0xa0, 0x8c, 0xac, 0xdf, 0xeb, 0x0a, 0x63, 0x04, 0x63, 0x6b, 0x18,
	0xa1, 0x5f, 0xb7, 0xb7, 0xcf, 0xa0, 0x2b, 0xa9, 0x1b, 0x74, 0x53, 0xca, 0x33, 0x31, 0x13, 0xf4,
	0x0d, 0x49, 0x7e, 0x91, 0xad, 0x74, 0x6c, 0x8b, 0xab, 0x12, 0xe5, 0x01, 0xfd, 0x92, 0xac, 0x1e,
	0xea, 0xda, 0x82, 0x63, 0x17, 0x48, 0xaf, 0x3a, 0x44, 0x9e, 0x3f, 0x8c, 0xe9, 0x9f, 0x8d, 0xbc,
	0x45, 0xe4, 0x4f, 0x3f, 0x4c, 0x0b, 0x2e, 0xc7, 0xd3, 0xed, 0xc3, 0x69, 0xc5, 0x0d, 0x54, 0x43,
	0x0f, 0xec, 0x0a, 0x8f, 0x5e, 0x55, 0x88, 0x8a, 0x1f, 0xc8, 0x76, 0xd1, 0x05, 0x4b, 0xbf, 0x23,
	0xc9, 0x9d, 0x83, 0xd6, 0xb2, 0xe0, 0xff, 0x9a, 0x95, 0x48, 0x9f, 0x53, 0xfc, 0x19, 0x90, 0xcd,
	0x82, 0x9e, 0x5d, 0xff, 0x51, 0x58, 0x98, 0xfc, 0x83, 0xae, 0xf7, 0x98, 0x96, 0xe4, 0x92, 0x83,
	0x03, 0xed, 0x6b, 0xf8, 0xa1, 0x53, 0xf2, 0xf9, 0x05, 0xad, 0x9f, 0xf1, 0x4b, 0xf3, 0x29, 0x7d,
	0x9a, 0x45, 0xd1, 0xe8, 0x40, 0x9c, 0x45, 0x6f, 0x48, 0xc2, 0xa1, 0x81, 0xe3, 0xe4, 0xf4, 0xc4,
	0x78, 0xe0, 0xcf, 0xbb, 0xb3, 0x8f, 0xc2, 0x34, 0xe0, 0x26, 0x7f, 0xa7, 0x72, 0xc2, 0xc5, 0x8f,
	0x67, 0x1b, 0xe1, 0xbd, 0x06, 0x23, 0xb0, 0x9f, 0x01, 0xd6, 0x25, 0xad, 0x26, 0xbc, 0x28, 0x71,
	0xb8, 0x2c, 0x71, 0xb1, 0x27, 0x17, 0x9f, 0xbc, 0x70, 0xac, 0x2d, 0x18, 0x09, 0xf6, 0x7e, 0xda,
	0x63, 0x6d, 0x47, 0xe8, 0xb7, 0xc0, 0x29, 0x7a, 0x3f, 0x6f, 0xd1, 0x23, 0x2a, 0x76, 0x64, 0x35,
	0x3e, 0x06, 0xff, 0x80, 0x9e, 0x84, 0x9a, 0xa6, 0x6b, 0xe4, 0xaf, 0xe4, 0x07, 0xa9, 0x1f, 0x0e,
	0xe1, 0xe8, 0x4a, 0xf7, 0xd2, 0xc3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xcd, 0x8c, 0xf4,
	0xb2, 0x05, 0x00, 0x00,
}
